    
free_design_page:
    path:     /
    defaults: {_controller: FreeDesignBundle:Default:index }


free_design_add_category:
    path:     /addCategory
    defaults: {_controller: FreeDesignBundle:Default:addCategory }
    
free_design_add_template:  
    path:     /addTemplate
    defaults: {_controller: FreeDesignBundle:Default:addTemplate }    

free_design_preview:  
    path:     /template/preview/{name}
    defaults: {_controller: FreeDesignBundle:Default:preview }    

free_design_template:  
    path:     /template/{name}
    defaults: {_controller: FreeDesignBundle:Default:showTemplate }    

#show itemps by category 

free_design_show_category:  
    path:     /category/{category}
    defaults: {_controller: FreeDesignBundle:Default:index }



free_design_template_download:  
    path:     /template/download/{name}
    defaults: {_controller: FreeDesignBundle:Default:downloadTemplate }    

# not implemented yet 
free_design_api_delete_Category:  
    path:     /api/delete
    defaults: {_controller: FreeDesignBundle:API:deleteCategory }    

free_design_api_add_Category:  
    path:     /api/add
    defaults: {_controller: FreeDesignBundle:API:addCategory }    


free_design_api_delete_Template:  
    path:     /api/deleteTemplate
    defaults: {_controller: FreeDesignBundle:API:deleteTemplate }    