    
free_design_page:
    path:     /
    defaults: {_controller:FreeDesignBundle:Default:index }

free_design_add_category:
    path:     /addCategory
    defaults: {_controller:FreeDesignBundle:Default:addCategory }
    
free_design_add_template:  
    path:     /addTemplate
    defaults: {_controller:FreeDesignBundle:Default:addTemplate }    